[pytest]
markers =
    regression: mark a test as regression scenario
    positive: mark a test as positive scenario
    negative: mark a test as negative scenario
    smoke: mark a test as smoke scenario
    valid: mark a test as valid scenario
    invalid: mark a test as invalid scenario
    deprecated: mark a test as deprecated scenario
    xfail: mark a test as xfail scenario
    error_handling: mark a test as error_handling scenario
    parametrize: mark a test as parametrize scenario
    edge: mark a test as edge scenario
