[pytest]
markers =
    regression: mark a test as regression scenario
    valid: mark a test as valid scenario
    duplicate: mark a test as duplicate scenario
    invalid: mark a test as invalid scenario
    positive: mark a test as positive scenario
    negative: mark a test as negative scenario
    edge: mark a test as edge scenario
    deprecation: mark a test as deprecation scenario
    error: mark a test as error scenario
    deprecated: mark a test as deprecated scenario
    smoke: mark a test as smoke scenario
    exception: mark a test as exception scenario
