[pytest]
markers =
    regression: mark a test as regression scenario
    smoke: mark a test as smoke scenario
    valid: mark a test as valid scenario
    positive: mark a test as positive scenario
    negative: mark a test as negative scenario
    invalid: mark a test as invalid scenario
    parametrize: mark a test as parametrize scenario
