# ********RoostGPT********
"""
Test generated by RoostGPT for test pythonBigProjectTest using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=_get_default_parser_da6898e1c5
ROOST_METHOD_SIG_HASH=_get_default_parser_61b2c6fc97


```
Scenario 1: Test when LUIGI_CONFIG_PARSER environment variable is not set
Details:
  TestName: test_get_default_parser_no_env
  Description: This test will validate that the function returns DEFAULT_PARSER when there's no LUIGI_CONFIG_PARSER environment variable set.
Execution:
  Arrange: unset or ignore the LUIGI_CONFIG_PARSER environment variable 
  Act: directly call the _get_default_parser() function
  Assert: checks if the result equals to DEFAULT_PARSER
Validation:
  This test is crucial to ensure that the function is to fall back on the default parser when there's no related environment variable set.

Scenario 2: Test when LUIGI_CONFIG_PARSER environment variable is set to a valid parser
Details:
  TestName: test_get_default_parser_valid_env
  Description: This test will validate the function's effect of returning the LUIGI_CONFIG_PARSER environment variable when it's set and it's a valid parser.
Execution:
  Arrange: Set the LUIGI_CONFIG_PARSER environment variable to a valid parser name
  Act: Call the _get_default_parser() function
  Assert: Verify if the function returns the valid parser you set
Validation:
  This scenario is important, it validates that the function correctly retrieves and returns a defined and valid LUIGI_CONFIG_PARSER environment variable as expected.

Scenario 3: Test when LUIGI_CONFIG_PARSER environment variable is set to an invalid parser
Details:
  TestName: test_get_default_parser_invalid_env
  Description: This test will check if the function is able to handle the situation when the LUIGI_CONFIG_PARSER environment variable is set to an invalid parser.
Execution:
  Arrange: Set the LUIGI_CONFIG_PARSER environment variable to an invalid parser name
  Act: Call the _get_default_parser() function
  Assert: Verify if the function returns the DEFAULT_PARSER
Validation:
  This scenario verifies function's fault tolerance and the ability to default to the DEFAULT_PARSER when an invalid parser is specified in the environment variable.
```

"""

# ********RoostGPT********
import logging
import os
import warnings
import pytest
from cfg_parser import LuigiConfigParser
from toml_parser import LuigiTomlParser
from core import _get_default_parser

class Test_CoreGetDefaultParser:
    
    @pytest.mark.regression
    def test_get_default_parser_no_env(self, monkeypatch):
        # Arrange
        monkeypatch.delenv('LUIGI_CONFIG_PARSER', raising=False)
        # Act
        result = _get_default_parser()
        # Assert
        assert result == 'cfg', 'Default parser is not returned when environment variable is not set'
    
    @pytest.mark.positive
    def test_get_default_parser_valid_env(self, monkeypatch):
        # Arrange
        monkeypatch.setenv('LUIGI_CONFIG_PARSER', 'toml')
        # Act
        result = _get_default_parser()
        # Assert
        assert result == 'toml', 'Function does not return the set parser from environment variable'
    
    @pytest.mark.negative
    def test_get_default_parser_invalid_env(self, monkeypatch):
        # Arrange
        monkeypatch.setenv('LUIGI_CONFIG_PARSER', 'invalid')
        # Act
        with warnings.catch_warnings(record=True) as w:
            result = _get_default_parser()
            # Assert
            assert len(w) == 1
            assert issubclass(w[-1].category, UserWarning)
            assert "Invalid parser: cfg" in str(w[-1].message)
        assert result == 'cfg', 'Function does not return the default parser when environment variable has invalid parser'

