# ********RoostGPT********
"""
Test generated by RoostGPT for test pythonBigProjectTest using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated by RoostGPT for test pythonBigProjectTest using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=getintdict_fed097f72d
ROOST_METHOD_SIG_HASH=getintdict_8dcd8d4d77


```
Scenario 1: Test fetching of integer dictionary from a valid section excluding DEFAULT
Details:
  TestName: test_fetch_intdict_valid_section
  Description: This test is intended to verify whether the given function is able to successfully return a dictionary of integer values from a defined section, excluding DEFAULT.
Execution:
  Arrange: Initialize a config parser object with a section having certain integer values and the DEFAULT section also populated. 
  Act: Invoke the getintdict function using an existing section as parameter.
  Assert: The resulting dictionary should match the expected output, excluding the DEFAULT section.
Validation:
  This test is vital as it validates the core functionality of 'getintdict' function, i.e., to fetch integer dict excluding DEFAULT.

Scenario 2: Test function behavior with a non-existing section
Details:
  TestName: test_fetch_intdict_non_existing_section
  Description: To test the function's behavior when supplied with a non-existing section name.
Execution:
  Arrange: Prepare a configparser object with some pre-defined named sections.
  Act: Call the method getintdict using a non-existent section name.
  Assert: The method should return an empty dictionary, as stated in its catch block.
Validation:
  It is crucial to check the getintdict function's robustness in handling non-existent sections. It should, in these cases, return an empty dictionary according to the functional specification.

Scenario 3: Test function with Non-integer values in the section
Details:
  TestName: test_fetch_intdict_non_integer_values
  Description: This test verifies how the function handles sections that also include non-integer values.
Execution:
  Arrange: Initiate a configparser object where a section contains both integer and non-integer values.
  Act: Invoke the getintdict method using the name of the prepared section.
  Assert: The returned dictionary needs to exclude non-integer keys-values pairs. No errors should be thrown irrespective of the data type.
Validation:
  The getintdict function is designed to parse only integer values. Therefore, it is critical to verify its behavior with different types of values. The function should effectively ignore non-integer pairs.

Scenario 4: Test function behavior with empty 'DEFAULT' section
Details:
  TestName: test_fetch_intdict_empty_default
  Description: This test checks how the function behaves when DEFAULT section is empty.
Execution:
  Arrange: Prepare a configparser object with an empty DEFAULT section and another section with some integer values.
  Act: Call the function getintdict using the prepared non-default section's name.
  Assert: It should return a dictionary including all the values from the tested section, as nothing is to be excluded due to an empty DEFAULT section.
Validation:
  It is necessary to confirm the function correctly handles empty DEFAULT sections, ensuring it doesn't over-exclude pairs due to wrong DEFAULT handling.
```
"""

# ********RoostGPT********
import os
import pytest
from configparser import ConfigParser, NoSectionError
from cfg_parser import LuigiConfigParser

class Test_LuigiConfigParserGetintdict:

    @pytest.mark.valid
    def test_fetch_intdict_valid_section(self):

        # Arrange
        config_parser = LuigiConfigParser()
        config_parser.add_section('section1')
        config_parser.set('section1', 'key1', '1')
        config_parser.set('section1', 'key2', '2')
        config_parser.set('DEFAULT', 'default_key', 'default')

        # Act
        result_dict = config_parser.getintdict('section1')

        # Assert
        assert result_dict == {"key1": 1, "key2": 2}

    @pytest.mark.valid
    def test_fetch_intdict_non_existing_section(self):

        # Arrange
        config_parser = LuigiConfigParser()
        config_parser.add_section('section1')
        config_parser.set('section1', 'key1', '1')
        config_parser.set('section1', 'key2', '2')
        
        # Act
        result_dict = config_parser.getintdict('non-existing-section')

        # Assert
        assert result_dict == {}

    @pytest.mark.invalid
    def test_fetch_intdict_non_integer_values(self):

        # Arrange
        config_parser = LuigiConfigParser()
        config_parser.add_section('section1')
        config_parser.set('section1', 'key1', '1')
        config_parser.set('section1', 'key2', 'string-value')
        
        # Act
        result_dict = config_parser.getintdict('section1')

        # Assert
        assert result_dict == {"key1": 1}

    @pytest.mark.valid
    def test_fetch_intdict_empty_default(self):

        # Arrange
        config_parser = LuigiConfigParser()
        config_parser.add_section('section1')
        config_parser.set('section1', 'key1', '1')
        config_parser.set('section1', 'key2', '2')
        
        # The default section would be empty in this case, and nothing would be excluded from section1

        # Act
        result_dict = config_parser.getintdict('section1')

        # Assert
        assert result_dict == {"key1": 1, "key2": 2}
