# ********RoostGPT********
"""
Test generated by RoostGPT for test pythonBigProjectTest using AI Type Open AI and AI Model gpt-4

ROOST_METHOD_HASH=_check_parser_a1d81ddd5b
ROOST_METHOD_SIG_HASH=_check_parser_326832c82e


Scenario 1: Test when the parser_class is enabled
Details:
  TestName: test_check_parser_enabled
  Description: This test is intended to verify that the function _check_parser does not raise an ImportError when the parser_class is enabled.
Execution:
  Arrange: Initialize an instance of a parser_class (either LuigiConfigParser or LuigiTomlParser) with the enabled property set to True.
  Act: Call the function _check_parser, passing the initialized parser_class and an arbitrary string as the parser parameter.
  Assert: Check that no ImportError is raised.
Validation:
  This test is important to confirm that the function behaves as expected when the parser_class is enabled. This is a basic functionality of the function and should work as intended.

Scenario 2: Test when the parser_class is not enabled
Details:
  TestName: test_check_parser_not_enabled
  Description: This test is intended to verify that the function _check_parser raises an ImportError with the appropriate message when the parser_class is not enabled.
Execution:
  Arrange: Initialize an instance of a parser_class (either LuigiConfigParser or LuigiTomlParser) with the enabled property set to False.
  Act: Call the function _check_parser, passing the initialized parser_class and an arbitrary string as the parser parameter.
  Assert: Check that an ImportError is raised, and that the error message matches the expected format.
Validation:
  This test is important to confirm that the function correctly raises an error when the parser_class is not enabled. This is a necessary error handling feature of the function, ensuring that the application fails fast in case of incorrect setup.

Scenario 3: Test with different parser strings
Details:
  TestName: test_check_parser_different_parsers
  Description: This test is intended to verify that the function _check_parser correctly inserts the provided parser string into the error message when the parser_class is not enabled.
Execution:
  Arrange: Initialize an instance of a parser_class (either LuigiConfigParser or LuigiTomlParser) with the enabled property set to False.
  Act: Call the function _check_parser, passing the initialized parser_class and different strings as the parser parameter.
  Assert: Check that an ImportError is raised, and that the error message contains the provided parser string.
Validation:
  This test is important to confirm that the function correctly uses the provided parser string in the error message. This helps provide more informative error messages to the user, allowing them to quickly identify and fix the issue.
"""

# ********RoostGPT********
import logging
import os
import warnings
import pytest
from unittest.mock import Mock
from cfg_parser import LuigiConfigParser
from toml_parser import LuigiTomlParser
from core import _check_parser

class Test_CoreCheckParser:

    @pytest.mark.smoke
    @pytest.mark.positive
    def test_check_parser_enabled(self):
        # Arrange
        parser_class = Mock(enabled=True)
        parser = 'any_parser'

        # Act & Assert
        try:
            _check_parser(parser_class, parser)
        except ImportError:
            pytest.fail("Unexpected ImportError !")

    @pytest.mark.smoke
    @pytest.mark.negative
    def test_check_parser_not_enabled(self):
        # Arrange
        parser_class = Mock(enabled=False)
        parser = 'any_parser'
        expected_error_message = (
            "Parser not installed yet. "
            "Please, install luigi with required parser:\n"
            "pip install luigi[{parser}]"
        ).format(parser=parser)

        # Act & Assert
        with pytest.raises(ImportError) as e:
            _check_parser(parser_class, parser)
        assert str(e.value) == expected_error_message

    @pytest.mark.regression
    @pytest.mark.negative
    @pytest.mark.parametrize(
        "parser", ['cfg', 'conf', 'ini', 'toml']
    )
    def test_check_parser_different_parsers(self, parser):
        # Arrange
        parser_class = Mock(enabled=False)
        expected_error_message = (
            "Parser not installed yet. "
            "Please, install luigi with required parser:\n"
            "pip install luigi[{parser}]"
        ).format(parser=parser)

        # Act & Assert
        with pytest.raises(ImportError) as e:
            _check_parser(parser_class, parser)
        assert str(e.value) == expected_error_message
