# ********RoostGPT********
"""
Test generated by RoostGPT for test pythonBigProjectTest using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated by RoostGPT for test pythonBigProjectTest using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated by RoostGPT for test pythonBigProjectTest using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=get_config_133e2e1291
ROOST_METHOD_SIG_HASH=get_config_8a95b2590c


Scenario 1: Testing the get_config method with a valid type of parser as an argument.
Details:
  TestName: test_get_config_with_valid_parser
  Description: This test verifies that the get_config method returns the correct parser class instance when an existing parser is given as an argument.
Execution:
  Arrange: Define a valid parser that exists in the PARSERS dictionary.
  Act: Pass the defined parser to the get_config function as a parameter.
  Assert: Confirm that the returned object is an instance of the right parser class.
Validation:
  This test ensures that the function correctly returns the appropriate parser class based on the parser argument. It's vital for the function to function correctly since the wrong parser can lead to unexpected behaviours.

Scenario 2: Testing the get_config method with no argument.
Details:
  TestName: test_get_config_with_no_argument
  Description: This test is intended to verify that the get_config method returns the default parser class instance when called without an argument.
Execution:
  Arrange: No specific preparation is needed as we're calling get_config without arguments.
  Act: Call the get_config function without any argument.
  Assert: Confirm that the returned object is an instance of the default parser class.
Validation:
  This test ensures that the function correctly returns the default parser class instance when it's called without an argument. This is important because we need to ensure that the function correctly falls back to the default parser when no specific parser is supplied.

Scenario 3: Testing get_config with an invalid parser as an argument.
Details:
  TestName: test_get_config_with_invalid_parser
  Description: This test is intended to verify that get_config function raises an exception when a non-existing parser is passed as an argument.
Execution:
  Arrange: Define an invalid parser that doesn't exist in the PARSERS dictionary.
  Act: Pass the defined parser to the get_config function as a parameter.
  Assert: Confirm that the function raises a suitable exception for a non-existing parser.
Validation:
  This test validates that the function correctly detects and handles invalid parsers. It's crucial because passing an invalid parser should not result in a parser instance but should instead give the user feedback that the parser is not correct.
"""

# ********RoostGPT********
import logging
import os
import pytest
import warnings
from cfg_parser import LuigiConfigParser
from toml_parser import LuigiTomlParser
from core import get_config

class Test_CoreGetConfig:
    
    @pytest.mark.positive
    @pytest.mark.smoke
    def test_get_config_with_valid_parser(self):
        parser = "toml"
        result = get_config(parser)
        
        assert isinstance(result, LuigiTomlParser), f"Expected instance of LuigiTomlParser, but got {type(result)}"
        
    @pytest.mark.positive
    @pytest.mark.regression
    def test_get_config_with_no_argument(self):
        result = get_config()

        assert isinstance(result, LuigiConfigParser), f"Expected instance of LuigiConfigParser, but got {type(result)}"
        
    @pytest.mark.negative
    @pytest.mark.regression
    def test_get_config_with_invalid_parser(self):
        parser = "invalid_parser"

        with pytest.raises(KeyError, match="The parser argument is not valid."):
            get_config(parser)
