# ********RoostGPT********
"""
Test generated by RoostGPT for test pythonBigProjectTest using AI Type Open AI and AI Model gpt-4

Test generated by RoostGPT for test pythonBigProjectTest using AI Type Open AI and AI Model gpt-4

ROOST_METHOD_HASH=getfloat_3dd718912f
ROOST_METHOD_SIG_HASH=getfloat_5677f79390


Scenario 1: Test when the section and option exist in the data
Details:
  TestName: test_getfloat_section_option_exist
  Description: This test is intended to verify that the correct data is returned when the section and option are found in the data.
Execution:
  Arrange: Initialize a ConfigParser object with a data dictionary containing known section and option.
  Act: Invoke the getfloat function with the known section and option.
  Assert: Check that the returned value is equal to the expected value of the section and option in the data dictionary.
Validation:
  This test ensures that the getfloat function correctly fetches and returns the value from the data when the section and option exist. This is crucial for the function's main functionality and business logic.

Scenario 2: Test when the section and option do not exist and a default value is provided
Details:
  TestName: test_getfloat_section_option_not_exist_default_provided
  Description: This test is intended to verify that the default value is returned when the section and option are not found in the data.
Execution:
  Arrange: Initialize a ConfigParser object with a data dictionary without the section and option to be requested.
  Act: Invoke the getfloat function with the non-existent section and option and a known default value.
  Assert: Check that the returned value is equal to the provided default value.
Validation:
  This test ensures that the getfloat function correctly returns the default value when the section and option are not found. This is important for the function's ability to handle missing data.

Scenario 3: Test when the section and option do not exist and no default value is provided
Details:
  TestName: test_getfloat_section_option_not_exist_no_default
  Description: This test is intended to verify that an exception is raised when the section and option are not found in the data and no default value is provided.
Execution:
  Arrange: Initialize a ConfigParser object with a data dictionary without the section and option to be requested.
  Act: Invoke the getfloat function with the non-existent section and option and no default value.
  Assert: Check that a KeyError exception is raised.
Validation:
  This test ensures that the getfloat function raises an exception when the section and option are not found and no default value is provided. This is essential for the function's error handling and ensuring it fails gracefully when required data is missing.
"""

# ********RoostGPT********
import pytest
from configparser import ConfigParser
from toml_parser import LuigiTomlParser

class Test_LuigiTomlParserGetfloat:
    @pytest.mark.positive
    def test_getfloat_section_option_exist(self):
        # Arrange
        config = LuigiTomlParser()
        config.data = {'section1': {'option1': 1.23}}
        section = 'section1'
        option = 'option1'
        expected_value = 1.23

        # Act
        actual_value = config.getfloat(section, option)

        # Assert
        assert actual_value == expected_value

    @pytest.mark.negative
    def test_getfloat_section_option_not_exist_default_provided(self):
        # Arrange
        config = LuigiTomlParser()
        config.data = {'section1': {'option1': 1.23}}
        section = 'section2'
        option = 'option2'
        default_value = 2.34

        # Act
        actual_value = config.getfloat(section, option, default=default_value)

        # Assert
        assert actual_value == default_value

    @pytest.mark.exception
    def test_getfloat_section_option_not_exist_no_default(self):
        # Arrange
        config = LuigiTomlParser()
        config.data = {'section1': {'option1': 1.23}}
        section = 'section2'
        option = 'option2'

        # Act and Assert
        with pytest.raises(KeyError):
            config.getfloat(section, option)
