# ********RoostGPT********
"""
Test generated by RoostGPT for test pythonBigProjectTest using AI Type Open AI and AI Model gpt-4

ROOST_METHOD_HASH=_get_with_default_aeb85b75c1
ROOST_METHOD_SIG_HASH=_get_with_default_19a36c0a1b


Scenario 1: Test the method with valid section and option
Details:
  TestName: test_get_with_default_valid_section_option
  Description: This test is intended to verify that the method correctly retrieves the value of a valid section/option, and does not raise any exceptions.
Execution:
  Arrange: Initialize a ConfigParser object with a sample configuration containing a valid section and option.
  Act: Invoke the _get_with_default method with the valid section and option.
  Assert: Verify that the method returns the correct value for the given section/option.
Validation:
  Rationalize: It's important to ensure that the method correctly retrieves values from the configuration, as this is its primary function.

Scenario 2: Test the method with invalid section and option
Details:
  TestName: test_get_with_default_invalid_section_option
  Description: This test is intended to verify that the method correctly handles a situation where an invalid section/option is requested.
Execution:
  Arrange: Initialize a ConfigParser object with a sample configuration.
  Act: Invoke the _get_with_default method with an invalid section and option.
  Assert: Verify that the method returns the default value provided in the parameters.
Validation:
  Rationalize: It's crucial to ensure that the method can gracefully handle invalid sections/options and return a default value when necessary.

Scenario 3: Test the method with a default value that doesn't match the expected type
Details:
  TestName: test_get_with_default_default_value_type_mismatch
  Description: This test is intended to verify that the method raises an exception if the default value provided does not match the expected type.
Execution:
  Arrange: Initialize a ConfigParser object with a sample configuration.
  Act: Invoke the _get_with_default method with a default value that does not match the expected type.
  Assert: Verify that the method raises an exception.
Validation:
  Rationalize: Ensuring that the method raises an exception when the default value doesn't match the expected type is important for maintaining type consistency.

Scenario 4: Test the method with dash-style option names
Details:
  TestName: test_get_with_default_dash_option
  Description: This test is intended to verify that the method can handle dash-style option names, but raises a DeprecationWarning.
Execution:
  Arrange: Initialize a ConfigParser object with a sample configuration containing a dash-style option name.
  Act: Invoke the _get_with_default method with the dash-style option name.
  Assert: Verify that the method returns the correct value and raises a DeprecationWarning.
Validation:
  Rationalize: It's important to ensure that the method can handle dash-style option names for backwards compatibility, but correctly warns the user about deprecation.
"""

# ********RoostGPT********
import os
import re
import warnings
import pytest
from configparser import ConfigParser, NoOptionError, NoSectionError, InterpolationError
from configparser import Interpolation, BasicInterpolation
from configuration.cfg_parser import LuigiConfigParser._get_with_default
from base_parser import BaseParser

class Test_LuigiConfigParserGetWithDefault:
    @pytest.mark.valid
    def test_get_with_default_valid_section_option(self):
        # Arrange
        config = ConfigParser()
        config.read_dict({'section': {'option': 'value'}})
        # Act
        result = _get_with_default(config.get, 'section', 'option', 'default')
        # Assert
        assert result == 'value'

    @pytest.mark.invalid
    def test_get_with_default_invalid_section_option(self):
        # Arrange
        config = ConfigParser()
        config.read_dict({'section': {'option': 'value'}})
        # Act
        result = _get_with_default(config.get, 'invalid_section', 'invalid_option', 'default')
        # Assert
        assert result == 'default'

    @pytest.mark.negative
    def test_get_with_default_default_value_type_mismatch(self):
        # Arrange
        config = ConfigParser()
        config.read_dict({'section': {'option': 'value'}})
        # Act & Assert
        with pytest.raises(TypeError):
            _get_with_default(config.get, 'section', 'option', default=1, expected_type=str)

    @pytest.mark.deprecation
    def test_get_with_default_dash_option(self):
        # Arrange
        config = ConfigParser()
        config.read_dict({'section': {'dash-option': 'value'}})
        # Act & Assert
        with warnings.catch_warnings(record=True) as w:
            warnings.simplefilter("always")
            result = _get_with_default(config.get, 'section', 'dash-option', 'default')
            assert len(w) == 1
            assert issubclass(w[-1].category, DeprecationWarning)
            assert result == 'value'
