# ********RoostGPT********
"""
Test generated by RoostGPT for test pythonBigProjectTest using AI Type Open AI and AI Model gpt-4

ROOST_METHOD_HASH=getintdict_fed097f72d
ROOST_METHOD_SIG_HASH=getintdict_8dcd8d4d77


Scenario 1: Test when section contains integer values
Details:
  TestName: test_getintdict_with_integer_values
  Description: This test is intended to verify that the function correctly converts values to integers and excludes keys from the 'DEFAULT' section.
Execution:
  Arrange: Initialize a ConfigParser object with a section containing keys and integer values, and 'DEFAULT' section with some keys.
  Act: Invoke the getintdict function with the section name as a parameter.
  Assert: Check if the returned dictionary contains the correct keys and integer values, and no keys from the 'DEFAULT' section.
Validation:
  This test is important to ensure that the function correctly converts string values to integers, which is a key part of its intended functionality.

Scenario 2: Test when section does not exist
Details:
  TestName: test_getintdict_with_non_existent_section
  Description: This test is intended to verify that the function returns an empty dictionary when the provided section does not exist.
Execution:
  Arrange: Initialize a ConfigParser object with some sections, but none matching the name to be passed to the function.
  Act: Invoke the getintdict function with a non-existent section name as a parameter.
  Assert: Check if the returned dictionary is empty.
Validation:
  This test is important to ensure that the function correctly handles the scenario where the provided section is not found, which aligns with the function's exception handling logic.

Scenario 3: Test when section contains non-integer values
Details:
  TestName: test_getintdict_with_non_integer_values
  Description: This test is intended to verify that the function raises a ValueError when it attempts to convert non-integer string values to integers.
Execution:
  Arrange: Initialize a ConfigParser object with a section containing keys and non-integer values.
  Act: Invoke the getintdict function with the section name as a parameter.
  Assert: Check if a ValueError is raised.
Validation:
  This test is important to ensure that the function correctly raises an error when it encounters values that it cannot convert to integers, which is a key part of its error handling logic.

Scenario 4: Test when the 'DEFAULT' section contains integer values
Details:
  TestName: test_getintdict_with_default_integer_values
  Description: This test is intended to verify that the function correctly excludes keys from the 'DEFAULT' section, even if they hold integer values.
Execution:
  Arrange: Initialize a ConfigParser object with a section and a 'DEFAULT' section both containing keys and integer values.
  Act: Invoke the getintdict function with the section name as a parameter.
  Assert: Check if the returned dictionary contains the correct keys and integer values from the section, and no keys from the 'DEFAULT' section.
Validation:
  This test is important to ensure that the function correctly excludes keys from the 'DEFAULT' section, even if they hold integer values. This is part of the business logic of the function.
"""

# ********RoostGPT********
import os
import re
import warnings
import pytest
from configparser import ConfigParser, NoOptionError, NoSectionError, InterpolationError
from configparser import Interpolation, BasicInterpolation
from base_parser import BaseParser
from cfg_parser import LuigiConfigParser

class Test_LuigiConfigParserGetintdict:

    @pytest.mark.positive
    def test_getintdict_with_integer_values(self):
        # Arrange
        parser = ConfigParser()
        parser.add_section('TestSection')
        parser.set('TestSection', 'key1', '1')
        parser.set('TestSection', 'key2', '2')
        parser.set('DEFAULT', 'key3', '3')

        # Act
        result = LuigiConfigParser.getintdict(parser, 'TestSection')

        # Assert
        assert result == {'key1': 1, 'key2': 2}

    @pytest.mark.negative
    def test_getintdict_with_non_existent_section(self):
        # Arrange
        parser = ConfigParser()
        parser.add_section('TestSection')

        # Act
        result = LuigiConfigParser.getintdict(parser, 'NonExistentSection')

        # Assert
        assert result == {}

    @pytest.mark.negative
    def test_getintdict_with_non_integer_values(self):
        # Arrange
        parser = ConfigParser()
        parser.add_section('TestSection')
        parser.set('TestSection', 'key1', 'value1')

        # Act and Assert
        with pytest.raises(ValueError):
            LuigiConfigParser.getintdict(parser, 'TestSection')

    @pytest.mark.positive
    def test_getintdict_with_default_integer_values(self):
        # Arrange
        parser = ConfigParser()
        parser.add_section('TestSection')
        parser.set('TestSection', 'key1', '1')
        parser.set('DEFAULT', 'key2', '2')

        # Act
        result = LuigiConfigParser.getintdict(parser, 'TestSection')

        # Assert
        assert result == {'key1': 1}
