# ********RoostGPT********
"""
Test generated by RoostGPT for test pythonBigProjectTest using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated by RoostGPT for test pythonBigProjectTest using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=get_3589554733
ROOST_METHOD_SIG_HASH=get_d2f3a08528


Scenario 1: Successful retrieval of config option
Details:
  TestName: test_get_success
  Description: This test validates that the get function retrieves the correct config option from the specified section when given valid inputs.
Execution:
  Arrange: A sample config file will be prepared with a specific section and option. A ConfigParser object will be created and will parse the sample file.
  Act: The get function will be invoked, passing the section and config option that exists in the sample file.
  Assert: The function should return the correct value of the config option from the specified section.
Validation:
  This verifies that get function correctly retrieves values from a configparser object, adhering to its key functionality and business requirements.

Scenario 2: Requested option not found
Details:
  TestName: test_get_no_option
  Description: This test validates that the get function correctly handles a NoOptionError if the requested option does not exist.
Execution:
  Arrange: A ConfigParser object will be created similar to scenario 1, but this time, the option that would be requested does not exist.
  Act: The get function will be invoked with the non-existing option.
  Assert: The function should raise NoOptionError.
Validation:
  This verifies that the function correctly handles non-existent options, raising the right exception and thus ensuring its operational integrity.

Scenario 3: Requested section not found
Details:
  TestName: test_get_no_section
  Description: This test validates that the get function correctly handles a NoSectionError if the requested section does not exist.
Execution:
  Arrange: Similar to scenario 2, but this time, the section that would be requested does not exist.
  Act: Invoke the get function with the non-existing section.
  Assert: Function should raise NoSectionError.
Validation:
  This verifies that the function correctly handles non-existent sections. Raising correct exceptions, ensures unexpected states are communicated back to the caller, ensuring robustness of the code.

Scenario 4: Interpolation error handling
Details:
  TestName: test_get_interpolation_error
  Description: Test that get function can correctly handle InterpolationError caused by referring to non-existing environment variables.
Execution:
  Arrange: ConfigParser object will be setup with a section and option that refers to a non-existent environment variable.
  Act: Invoke get function for the option that relies on the non-existent variable.
  Assert: Function should raise an InterpolationError.
Validation:
  This verifies that configparser can handle InterpolationErrors correctly, this is crucial in maintaining the correctness of configparser when dealing with environment variables which enhances its reliability.
"""

# ********RoostGPT********
import os
import pytest
import warnings
from configparser import ConfigParser, NoOptionError, NoSectionError, InterpolationError
from cfg_parser import LuigiConfigParser

@pytest.mark.testing   
class Test_LuigiConfigParserGet:
    
    @pytest.mark.positive
    def test_get_success(self):
        # Arrange
        parser = ConfigParser()
        parser.add_section('Section1')
        parser.set('Section1', 'option1', 'value1')
        lg = LuigiConfigParser(parser)

        # Act
        result = lg.get('Section1', 'option1')

        # Assert
        assert result == 'value1'

    @pytest.mark.negative
    def test_get_no_option(self):
        # Arrange
        parser = ConfigParser()
        parser.add_section('Section1')
        lg = LuigiConfigParser(parser)

        # Act / Assert
        with pytest.raises(NoOptionError):
            lg.get('Section1', 'non_existing_option')

    @pytest.mark.negative
    def test_get_no_section(self):
        # Arrange
        parser = ConfigParser()
        lg = LuigiConfigParser(parser)

        # Act / Assert
        with pytest.raises(NoSectionError):
            lg.get('non_existing_section', 'option1')

    @pytest.mark.negative
    def test_get_interpolation_error(self):
        os.environ.pop('NON_EXISTENT_ENV_VAR', None) # ensuring the variable doesn't exist
        parser = ConfigParser()
        parser.add_section('Section1')
        parser.set('Section1', 'option1', '%(NON_EXISTENT_ENV_VAR)s') # referring a non-existing environment variable
        lg = LuigiConfigParser(parser)

        # Act / Assert
        with pytest.raises(InterpolationError):
            lg.get('Section1', 'option1')
