# ********RoostGPT********
"""
Test generated by RoostGPT for test pythonBigProjectTest using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=add_config_path_388d3ffdb1
ROOST_METHOD_SIG_HASH=add_config_path_05e54720ac


```
Scenario 1: Test successful addition of configuration path and reloading of configurations
Details:
  TestName: test_add_config_path_successfully
  Description: The test is intended to verify if the configuration path is added successfully and the configurations are successfully reloaded thereafter. The main business logic here is the reloading of configurations after adding a configuration path.
Execution:
  Arrange: Initialize a path to be added to the config_paths list on the class.
  Act: Invoke the add_config_path function on the class, passing in the initialized path.
  Assert: Check if the configuration path was added to the cls._config_paths list and if cls.reload() was invoked.
Validation:
  Rationale: This test ensures that configuration paths can be successfully added and configurations reloaded thereafter. This supports the function's specifications and business 
requirements, as the function should be able to add paths and reload configurations correctly.

Scenario 2: Test multiple addition of the same configuration path 
Details:
  TestName: test_add_config_path_repeatedly
  Description: This test is intended to verify if the function add_config_path can handle multiple attempts to add the same configuration path. The business logic enclosed here pertains to the fact that the same path should not affect the reload functionality.
Execution:
  Arrange: Initialize a path to be added to the config_paths list on the class.
  Act: Invoke the add_config_path function on the class, passing in the initialized path multiple times.
  Assert: Check that the cls._config_paths list contains multiple instances of the path and that cls.reload() was invoked each time.
Validation:
  Rationale: This test validates whether or not adding the same path repeatedly affects reloading. This correlates directly with the functionality's business requirements and specifications that imply the system should reload configurations regardless of the uniqueness of the path.

Scenario 3: Test empty configuration path addition 
Details:
  TestName: test_add_config_path_empty
  Description: The test is intended to verify if the function add_config_path can handle attempts to add an empty path.
Execution:
  Arrange: Initialize an empty path.
  Act: Invoke the add_config_path function on the class, passing in the empty path.
  Assert: Check if the empty path was added to the cls._config_paths list and the cls.reload() was invoked.
Validation:
  Rationale: This test fills the gap by verifying if the function operates as expected when provided with a parameter that is within valid parameters yet potentially problematic. This reflects the business requirement for the function to handle different valid inputs.
```
"""

# ********RoostGPT********
import pytest
import logging
from unittest.mock import patch
from base_parser import BaseParser

class Test_BaseParserAddConfigPath:

    @pytest.mark.positive
    def test_add_config_path_successfully(self):
        # Arrange
        path = '/config/test_dev'
        with patch.object(BaseParser, 'reload', return_value=None) as mock_reload:
            # Act
            BaseParser.add_config_path(path)
            # Assert
            assert path in BaseParser._config_paths
            mock_reload.assert_called_once()

    @pytest.mark.negative
    def test_add_config_path_repeatedly(self):
        # Arrange
        path = '/config/test_dev_1'
        with patch.object(BaseParser, 'reload', return_value=None) as mock_reload:
            # Act
            for _ in range(5):
                BaseParser.add_config_path(path)
            # Assert
            assert BaseParser._config_paths.count(path) == 5
            assert mock_reload.call_count == 5

    @pytest.mark.negative
    def test_add_config_path_empty(self):
        # Arrange
        path = ''
        with patch.object(BaseParser, 'reload', return_value=None) as mock_reload:
            # Act
            BaseParser.add_config_path(path)
            # Assert
            assert path in BaseParser._config_paths
            mock_reload.assert_called_once()
