# ********RoostGPT********
"""
Test generated by RoostGPT for test pythonBigProjectTest using AI Type Open AI and AI Model gpt-4

Test generated by RoostGPT for test pythonBigProjectTest using AI Type Open AI and AI Model gpt-4

ROOST_METHOD_HASH=add_config_path_388d3ffdb1
ROOST_METHOD_SIG_HASH=add_config_path_05e54720ac


Scenario 1: Adding a new valid path to the list of configuration paths
Details:
  TestName: test_add_valid_config_path
  Description: This test verifies that the function add_config_path correctly adds a new valid path to the list of configuration paths and triggers a reload.
Execution:
  Arrange: Initialize a class object and an empty list for _config_paths. Also, prepare a valid path string.
  Act: Invoke the add_config_path function with the valid path string.
  Assert: Check if the new path has been correctly added to _config_paths and if the reload function has been triggered.
Validation:
  This test is important to ensure that the function correctly handles valid paths and updates the configuration appropriately. This is a fundamental requirement for the function.

Scenario 2: Adding an invalid path to the list of configuration paths
Details:
  TestName: test_add_invalid_config_path
  Description: This test verifies that the function add_config_path correctly handles the addition of an invalid path to the list of configuration paths and triggers a reload.
Execution:
  Arrange: Initialize a class object and an empty list for _config_paths. Also, prepare an invalid path string.
  Act: Invoke the add_config_path function with the invalid path string.
  Assert: Check if the invalid path has been added to _config_paths and if the reload function has been triggered.
Validation:
  This test is important to ensure that the function correctly handles invalid paths. It should either reject such paths or handle them gracefully to prevent potential issues with the configuration.

Scenario 3: Adding a duplicate path to the list of configuration paths
Details:
  TestName: test_add_duplicate_config_path
  Description: This test verifies that the function add_config_path correctly handles the addition of a duplicate path to the list of configuration paths and triggers a reload.
Execution:
  Arrange: Initialize a class object and a list for _config_paths containing a path string. Also, prepare a duplicate of the existing path string.
  Act: Invoke the add_config_path function with the duplicate path string.
  Assert: Check if the duplicate path has been added to _config_paths and if the reload function has been triggered.
Validation:
  This test is important to ensure that the function correctly handles duplicate paths. It should either reject such paths or handle them gracefully to prevent potential issues with the configuration.
"""

# ********RoostGPT********
import logging
import pytest
from unittest.mock import MagicMock
from base_parser import BaseParser


class Test_BaseParserAddConfigPath:

    @pytest.mark.positive
    def test_add_valid_config_path(self):
        # Arrange
        base_parser = BaseParser()
        base_parser._config_paths = []
        base_parser.reload = MagicMock()
        valid_path = "/valid/path"

        # Act
        base_parser.add_config_path(valid_path)

        # Assert
        assert valid_path in base_parser._config_paths
        base_parser.reload.assert_called_once()

    @pytest.mark.negative
    def test_add_invalid_config_path(self):
        # Arrange
        base_parser = BaseParser()
        base_parser._config_paths = []
        base_parser.reload = MagicMock()
        invalid_path = "invalid::path"

        # Act
        base_parser.add_config_path(invalid_path)

        # Assert
        assert invalid_path in base_parser._config_paths
        base_parser.reload.assert_called_once()

    @pytest.mark.negative
    def test_add_duplicate_config_path(self):
        # Arrange
        base_parser = BaseParser()
        base_parser._config_paths = ["/path"]
        base_parser.reload = MagicMock()
        duplicate_path = "/path"

        # Act
        base_parser.add_config_path(duplicate_path)

        # Assert
        assert base_parser._config_paths.count(duplicate_path) == 2
        base_parser.reload.assert_called_once()
