# ********RoostGPT********
"""
Test generated by RoostGPT for test pythonBigProjectTest using AI Type Open AI and AI Model gpt-4

Test generated by RoostGPT for test pythonBigProjectTest using AI Type Open AI and AI Model gpt-4

ROOST_METHOD_HASH=_get_default_parser_da6898e1c5
ROOST_METHOD_SIG_HASH=_get_default_parser_61b2c6fc97


```
Scenario 1: Test the default behavior of _get_default_parser function when LUIGI_CONFIG_PARSER is not set in the environment.
Details:
  TestName: test_default_behavior_without_LUIGI_CONFIG_PARSER
  Description: This test is intended to verify that the function returns the DEFAULT_PARSER when the environment variable LUIGI_CONFIG_PARSER is not set.
Execution:
  Arrange: No special setup is required.
  Act: Invoke the _get_default_parser method with no parameters.
  Assert: Check that the returned value is DEFAULT_PARSER.
Validation:
  The test is important to ensure that the function behaves as expected in its most common use case, when no specific parser is set in the environment.

Scenario 2: Test the behavior of _get_default_parser function when LUIGI_CONFIG_PARSER is set to a valid parser in the environment.
Details:
  TestName: test_valid_LUIGI_CONFIG_PARSER
  Description: This test is intended to verify that the function returns the parser set in the LUIGI_CONFIG_PARSER environment variable if it exists in the PARSERS list.
Execution:
  Arrange: Set the LUIGI_CONFIG_PARSER environment variable to a valid parser that exists in the PARSERS list.
  Act: Invoke the _get_default_parser method with no parameters.
  Assert: Check that the returned value is the parser set in the LUIGI_CONFIG_PARSER environment variable.
Validation:
  The test is important to ensure that the function correctly reads and uses the LUIGI_CONFIG_PARSER environment variable when it is set to a valid parser.

Scenario 3: Test the behavior of _get_default_parser function when LUIGI_CONFIG_PARSER is set to an invalid parser in the environment.
Details:
  TestName: test_invalid_LUIGI_CONFIG_PARSER
  Description: This test is intended to verify that the function returns the DEFAULT_PARSER and issues a warning when the LUIGI_CONFIG_PARSER environment variable is set to a parser that does not exist in the PARSERS list.
Execution:
  Arrange: Set the LUIGI_CONFIG_PARSER environment variable to an invalid parser that does not exist in the PARSERS list.
  Act: Invoke the _get_default_parser method with no parameters.
  Assert: Check that the returned value is DEFAULT_PARSER and a warning has been issued.
Validation:
  The test is important to ensure that the function handles invalid values in the LUIGI_CONFIG_PARSER environment variable by falling back to the DEFAULT_PARSER and issuing a warning.
```
"""

# ********RoostGPT********
import os
import warnings
import pytest
from core import _get_default_parser

class Test_CoreGetDefaultParser:

    @pytest.mark.regression
    def test_default_behavior_without_LUIGI_CONFIG_PARSER(self):
        # Arrange
        if 'LUIGI_CONFIG_PARSER' in os.environ:
            del os.environ['LUIGI_CONFIG_PARSER']

        # Act
        result = _get_default_parser()

        # Assert
        assert result == 'cfg'

    @pytest.mark.regression
    def test_valid_LUIGI_CONFIG_PARSER(self):
        # Arrange
        os.environ['LUIGI_CONFIG_PARSER'] = 'toml'

        # Act
        result = _get_default_parser()

        # Assert
        assert result == 'toml'

    @pytest.mark.regression
    def test_invalid_LUIGI_CONFIG_PARSER(self):
        # Arrange
        os.environ['LUIGI_CONFIG_PARSER'] = 'invalid_parser'

        # Act
        with warnings.catch_warnings(record=True) as w:
            result = _get_default_parser()

        # Assert
        assert len(w) == 1
        assert issubclass(w[-1].category, UserWarning)
        assert str(w[-1].message) == "Invalid parser: cfg"
        assert result == 'cfg'
