# ********RoostGPT********
"""
Test generated by RoostGPT for test pythonBigProjectTest using AI Type Open AI and AI Model gpt-4

ROOST_METHOD_HASH=_interpolate_env_ea5eb159c9
ROOST_METHOD_SIG_HASH=_interpolate_env_9d7c1514cf


```
Scenario 1: Test when environment variable exists and is used in the value
Details:
  TestName: test_interpolate_env_with_existing_envvar
  Description: This test is intended to verify that the function correctly interpolates an environment variable that exists and is used in the value.
Execution:
  Arrange: Set an environment variable to a specific value.
  Act: Invoke the function with a value string that includes the environment variable.
  Assert: The output should be the input string with the environment variable replaced by its value.
Validation:
  This test validates that the function correctly interpolates environment variables that exist. This is important as the function's primary purpose is to replace references to environment variables with their actual values.

Scenario 2: Test when environment variable does not exist but is used in the value
Details:
  TestName: test_interpolate_env_with_missing_envvar
  Description: This test is intended to verify that the function raises an InterpolationMissingEnvvarError when the value string references a non-existent environment variable.
Execution:
  Arrange: Ensure the environment does not contain a certain variable.
  Act: Invoke the function with a value string that includes the non-existent environment variable.
  Assert: An InterpolationMissingEnvvarError should be raised.
Validation:
  This test validates that the function correctly raises an error when a referenced environment variable does not exist. This is important as the function should not return a value with unresolved environment variables.

Scenario 3: Test when value does not contain any environment variable
Details:
  TestName: test_interpolate_env_without_envvar
  Description: This test is intended to verify that the function correctly returns the input value when it does not contain any references to environment variables.
Execution:
  Arrange: No specific setup is required.
  Act: Invoke the function with a value string that does not include any environment variables.
  Assert: The output should be the same as the input value.
Validation:
  This test validates that the function correctly handles values that do not contain environment variables. This ensures that the function can correctly handle a variety of input values.

Scenario 4: Test when value contains multiple environment variables
Details:
  TestName: test_interpolate_env_with_multiple_envvars
  Description: This test is intended to verify that the function correctly interpolates multiple environment variables that exist and are used in the value.
Execution:
  Arrange: Set multiple environment variables to specific values.
  Act: Invoke the function with a value string that includes the environment variables.
  Assert: The output should be the input string with the environment variables replaced by their values.
Validation:
  This test validates that the function correctly handles multiple environment variables in a single value. This ensures that the function can handle complex inputs.
"""

# ********RoostGPT********
import os
import pytest
from configparser import InterpolationMissingEnvvarError
from cfg_parser import _interpolate_env

class Test_EnvironmentInterpolationInterpolateEnv:
    @pytest.mark.positive
    def test_interpolate_env_with_existing_envvar(self):
        # Arrange
        os.environ['EXISTING_VAR'] = 'test_value'
        # Act
        result = _interpolate_env('option', 'section', '${EXISTING_VAR}')
        # Assert
        assert result == 'test_value'
    
    @pytest.mark.negative
    def test_interpolate_env_with_missing_envvar(self):
        # Arrange
        if 'NON_EXISTING_VAR' in os.environ:
            del os.environ['NON_EXISTING_VAR']
        # Act & Assert
        with pytest.raises(InterpolationMissingEnvvarError):
            _interpolate_env('option', 'section', '${NON_EXISTING_VAR}')

    @pytest.mark.positive
    def test_interpolate_env_without_envvar(self):
        # Act
        result = _interpolate_env('option', 'section', 'value_without_env_var')
        # Assert
        assert result == 'value_without_env_var'
    
    @pytest.mark.positive
    def test_interpolate_env_with_multiple_envvars(self):
        # Arrange
        os.environ['EXISTING_VAR1'] = 'test_value1'
        os.environ['EXISTING_VAR2'] = 'test_value2'
        # Act
        result = _interpolate_env('option', 'section', '${EXISTING_VAR1}${EXISTING_VAR2}')
        # Assert
        assert result == 'test_value1test_value2'
