# ********RoostGPT********
"""
Test generated by RoostGPT for test pythonBigProjectTest using AI Type Open AI and AI Model gpt-4

ROOST_METHOD_HASH=get_6fbd4744a7
ROOST_METHOD_SIG_HASH=get_d2f3a08528


Scenario 1: Test when the section and option are present in the data
Details:
  TestName: test_get_with_section_option_present
  Description: This tests the case when the section and option are present in the data. The function is expected to return the correct value.
Execution:
  Arrange: Initialize the data with a specific section and option and their corresponding value.
  Act: Call the function get with the specific section and option.
  Assert: Check if the returned value is same as the expected value.
Validation:
  This test is important as it verifies the basic functionality of the function, which is to retrieve the correct value when the section and option are present.

Scenario 2: Test when the section and option are not present, and no default is provided
Details:
  TestName: test_get_with_no_section_option_no_default
  Description: This tests the case when the section and option are not present in the data and no default value is provided. The function is expected to raise a KeyError.
Execution:
  Arrange: Initialize the data without the specific section and option.
  Act: Call the function get with the specific section and option.
  Assert: Check if a KeyError is raised.
Validation:
  This test is important as it verifies the function's error handling when the requested section and option are not present and no default value is provided.

Scenario 3: Test when the section and option are not present, but a default is provided
Details:
  TestName: test_get_with_no_section_option_with_default
  Description: This tests the case when the section and option are not present in the data but a default value is provided. The function is expected to return the default value.
Execution:
  Arrange: Initialize the data without the specific section and option. Prepare a default value.
  Act: Call the function get with the specific section and option and the default value.
  Assert: Check if the returned value is the default value.
Validation:
  This test is important as it verifies the function's capability to return a default value when the requested section and option are not present in the data.
"""

# ********RoostGPT********
import pytest
import os.path
from configparser import ConfigParser
from typing import Any, Dict
from base_parser import BaseParser
from freezing import recursively_freeze
import toml
from toml_parser import LuigiTomlParser

class Test_LuigiTomlParserGet:

    @pytest.mark.positive
    def test_get_with_section_option_present(self):
        # Arrange
        parser = LuigiTomlParser()
        parser.data = {'section': {'option': 'value'}}
        # Act
        result = parser.get('section', 'option')
        # Assert
        assert result == 'value'

    @pytest.mark.negative
    def test_get_with_no_section_option_no_default(self):
        # Arrange
        parser = LuigiTomlParser()
        parser.data = {'different_section': {'different_option': 'value'}}
        # Act & Assert
        with pytest.raises(KeyError):
            parser.get('section', 'option')

    @pytest.mark.positive
    def test_get_with_no_section_option_with_default(self):
        # Arrange
        parser = LuigiTomlParser()
        parser.data = {'different_section': {'different_option': 'value'}}
        default = 'default_value'
        # Act
        result = parser.get('section', 'option', default=default)
        # Assert
        assert result == default
